default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: financeflick_development

test:
  <<: *default
  database: financeflick_test

production:
  <<: *default
  database: financeflick_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  sslmode: verify-full
  sslrootcert: <%= ENV['DB_SSL_ROOT_CERT'] %>
  sslkey: <%= ENV['DB_SSL_KEY'] %>
  sslcert: <%= ENV['DB_SSL_CERT'] %>
